# Generated by Django 5.2.10 on 2026-01-13 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employeeprofile_date_of_birth_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
