# Generated by Django 5.2.10 on 2026-01-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='address_line1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='college_cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='college_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='school_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='school_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
