# Generated by Django 5.1.5 on 2026-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ticket_ticketupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In_Progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed')], default='Open', max_length=20),
        ),
    ]
